server:
  port: 8899

spring:
  datasource:
    druid:
      url: jdbc:mysql://47.113.89.235:3306/resume_reading?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true&useOldAliasMetadataBehavior=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

