server:
  port: 8899

spring:
  datasource:
    druid:
      url: jdbc:mysql://47.113.89.235:3306/resume_reading?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true&useOldAliasMetadataBehavior=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
  jpa:
    show-sql: true
  redis:
    host: 47.113.89.235
    port: 6379
    jedis:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: 8
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0
    # 数据库连接超时时间，2.0 中该参数的类型为Duration,这里在配置的时候需要指明单位
    timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.resume.mapper : debug


upload:
  product:
    images: images